name: pushdics.yml

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@main

    - run: sudo apt-get install doxygen
    - run: sudo apt-get install graphviz
    - run: doxygen doxconf
    
    - name: Push git subdir as branch

    uses: s0/git-publish-subdir-action@v2.4.0

    env:
      REPO: self
      BRANCH: gh-pages
      FOLDER: DOCS/html
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      